version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  file_manager:
    build: ./file_manager
    container_name: file-manager
    working_dir: /app
    volumes:
      - ./file_manager:/app/file_manager
    environment:
      - PYTHONPATH=/app
    command: celery -A file_manager.celery_app worker --loglevel=info
    depends_on:
      - redis

  create_testcase:
    build: ./create_testcase
    container_name: create-testcase
    working_dir: /app
    volumes:
      - ./create_testcase:/app/create_testcase
    environment:
      - PYTHONPATH=/app
    command: celery -A create_testcase.celery_app worker --loglevel=info
    depends_on:
      - redis
