version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: bitnami/kafka:3.7
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - zookeeper


  file_manager:
    build:
      context: .
      dockerfile: file_manager/Dockerfile
    container_name: file-manager
    working_dir: /app
    volumes:
      - ./file_manager:/app/file_manager
      - ./kafka_common:/app/kafka_common
      - ../../scripts:/app/scripts
    environment:
      - PYTHONPATH=/app
    ports:
      - "8001:8001"
    depends_on:
      - kafka

  create_testcase:
    build:
      context: .
      dockerfile: create_testcase/Dockerfile
    container_name: create-testcase
    working_dir: /app
    volumes:
      - ./create_testcase:/app/create_testcase
      - ./kafka_common:/app/kafka_common
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    depends_on:
      - kafka