version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  file_manager:
    build: ./file_manager
    container_name: file-manager
    working_dir: /app
    volumes:
      - ./file_manager:/app/file_manager
    environment:
      - PYTHONPATH=/app
#    command: celery -A file_manager.celery_app worker --loglevel=info
#    depends_on:
#      - redis

  create_testcase:
    build: ./create_testcase
    container_name: create-testcase
    working_dir: /app
    volumes:
      - ./create_testcase:/app/create_testcase
    environment:
      - PYTHONPATH=/app
#    command: celery -A create_testcase.celery_app worker --loglevel=info
#    depends_on:
#      - redis

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
