version: '3.8'

networks:
  default:
    external: true
    name: shared_net

services:
  file_manager:
    build:
      context: .
      dockerfile: file_manager/Dockerfile
    container_name: file-manager
    working_dir: /app
    volumes:
      - ./file_manager:/app/file_manager
      - ./kafka_common:/app/kafka_common
      - ./grpc:/app/grpc
      - ../../scripts:/app/scripts
    environment:
      - PYTHONPATH=/app/file_manager:/app/file_manager/grpc_internal
    ports:
      - "8001:8001"
    networks:
      - default

  create_testcase:
    build:
      context: .
      dockerfile: input-generator-service/Dockerfile
    container_name: create-testcase
    working_dir: /app
    volumes:
      - ./input-generator-service:/app/input-generator-service
      - ./kafka_common:/app/kafka_common
      - ./grpc:/app/grpc
    environment:
      - PYTHONPATH=/app/input-generator-service:/app/input-generator-service/grpc_internal
    ports:
      - "8000:8000"
    networks:
      - default

  code-runner:
    build:
      context: .
      dockerfile: execution-service/Dockerfile
    container_name: code-runner
    working_dir: /app
    volumes:
      - ./execution-service:/app/execution-service
      - ./kafka_common:/app/kafka_common
      - /var/run/docker.sock:/var/run/docker.sock
      - ./grpc:/app/grpc
    environment:
      - PYTHONPATH=/app/execution-service:/app/execution-service/grpc_internal
    ports:
      - "8002:8002"
    networks:
      - default

  auth:
    build:
      context: .
      dockerfile: auth_server/Dockerfile
    container_name: auth
    restart: always
    env_file:
      - ./auth_server/.env
    environment:
      - PYTHONPATH=/app/auth_server:/app/auth_server/grpc_internal
    volumes:
      - ./auth_server:/app/auth_server
      - ./grpc:/app/grpc
    ports:
      - "9000:9000"
    networks:
      - default

  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    container_name: orchestrator
    working_dir: /app
    volumes:
      - ./orchestrator:/app/orchestrator
      - ./grpc:/app/grpc
    environment:
      - PYTHONPATH=/app/orchestrator:/app/orchestrator/grpc_internal
    ports:
      - "8003:8003"
    networks:
      - default

  bff:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    restart: always
    volumes:
      - ./api-gateway:/app/api-gateway
      - ./grpc:/app/grpc
    ports:
      - "9001:9001"
    networks:
      - default
